#!/usr/bin/python3
import os
import py_compile

# Get the file name from the PYFILE environment variable
file_name = os.environ.get('PYFILE')

# Compile the file and save the bytecode to a new file with a ".pyc" extension
py_compile.compile(file_name, cfile=f"{file_name}c")

# Print the contents of the compiled file to the console
with open(f"{file_name}c", 'rb') as compiled_file:
    print(compiled_file.read())
